### ISSUE TITLE
2015标准有没有支持计划啊

### ISSUE THREAD

**Issue by yangjh-xbmu** [Haixing-Hu/GBT7714-2005-BibTeX-Style#11]
GB/T 7714-2015 《信息与文献参考文献著录规则》已经实施了，有没有支持计划呢？

**Comment by Liam0205** [comment]
@haixing-hu
海星你好。

我是 CTeX 套装的维护者，现有计划将 GBT7714 系列 BibStyle 加入新版的 CTeX 套装。
GBT7714 最新已经更新到了 2015，但是我注意到本项目的开发已近停滞。
请问是否有更新计划呢？

Harry-Chen/CTeX#10

**Comment by Harry-Chen** [comment]
楼上比我快一步啊...
那个链接指向的仓库是私有的，因此你得到404是正常的...

**Comment by Harry-Chen** [comment]
@LiamHuang0205 你能提供相应国标规范吗

On 周三, 3月 02, 2016 at 1:03 上午, Haixing Hu < notifications@github.com [notifications@github.com] > wrote:
@Harry-Chen [https://github.com/Harry-Chen] ，本项目开发并没有停止啊，只是因为我的论文写好了所以并没有必要再修改代码了，因为也没有人向我反映问题。偶尔有issue我还是会继续跟进修改的。事实上我并不知道
GBT7714 已经更新到2015版了😓，不知道哪里可以下载到2015版的标准文件，我可以下载下来看一下抽空更新一下符合最新标准。

—
Reply to this email directly or view it on GitHub
[https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style/issues/11#issuecomment-190815821] .[https://github.com/notifications/beacon/ACsGj3sBr1Fi6e2Cxc4nB8gTKceDccs2ks5ppHFbgaJpZM4G7acG.gif]

**Comment by gloomykeel** [comment]
[GBT 7714-2015信息与文献 参考文献著录规则.pdf](https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style/files/153951/GBT.7714-2015.pdf)

刚好我这里之前搜集了有~

**Comment by Harry-Chen** [comment]
赞赞赞！

On 周三, 3月 02, 2016 at 10:04 上午, gloomykeel < notifications@github.com [notifications@github.com] > wrote:
GBT 7714-2015信息与文献 参考文献著录规则.pdf
[https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style/files/153951/GBT.7714-2015.pdf]

刚好我这里之前搜集了有~

—
Reply to this email directly or view it on GitHub
[https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style/issues/11#issuecomment-191017941] .[https://github.com/notifications/beacon/ACsGj6WMmuV6ofi3Kw-anoYohf-ib-iFks5ppPAYgaJpZM4G7acG.gif]

**Comment by songjinghe** [comment]
这里有两个现成的，然而不太会用。。。
https://github.com/hushidong/biblatex-gb7714-2015
https://github.com/zepinglee/gbt-7714-2015
