### ISSUE TITLE
多个作者的格式问题

### ISSUE THREAD

**Issue by luopeixiang** [Haixing-Hu/GBT7714-2005-BibTeX-Style#19]
![image](https://user-images.githubusercontent.com/16150164/35096147-0a7762fa-fc86-11e7-9723-89571f56bdb5.png)

如图所示，当一个文献出现3个以上的作者时，出现et.al 而不是中文的“，等”
编译的时候我用的是下面的命令：
`xelatex foo.tex`
`bibtex foo.aux`
`xelatex foo.tex`
`xelatex foo.tex`
这个过程并没有出现错误信息，为什么会这样呢？

**Comment by luopeixiang** [comment]
已经找到问题的解决方法了：
在`bibtex foo.aux`命令执行之后，
会在工作目录生成foo.bbl文件，
将foo.bbl文本文件中的`et~al`全部替换成`等`即可。
修改后再编译的结果如下：
![image](https://user-images.githubusercontent.com/16150164/35102320-93b22f2a-fc9d-11e7-82f1-49f2782aefc6.png)


以上是我的解决方法，仅供参考。
平台：Ubuntu16.04LTS。

**Comment by ruicx** [comment]
看了一下 [源码](https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style/blob/master/gbt7714-2005.bst) 的489-499行，发现在 `.bit` 文件里加上 `language={zh},` 就可以了，不需要手动修改。下面是一个例子：

``` bittex
@article{CT系统成像及参数标定,
    title={CT系统成像及参数标定},
    author={甲 and 已 and 丙 and 丁},
    journal={学报(自然科学版)},
    number={4},
    year={2018},
    language={zh},
}
```
