### ISSUE TITLE
Possible to relicense under LPPL?

### ISSUE THREAD

**Issue by alick** [Haixing-Hu/GBT7714-2005-BibTeX-Style#8]
Is it possible to relicense the work under LPPL, which is commonly used in latex packages and classes? GPL is incompatible with LPPL, so that it is not practical for existing LPPL-licenced projects to reuse your work...

**Comment by zepinglee** [comment]
thuthesis 要用这个吗？

**Comment by alick** [comment]
@zepinglee 如果许可证兼容的话，我觉得使用这个挺好，不重新造轮子。
